version: "3.7"

services:
  web:
    image: nginx:latest
    ports:
        - "4500:80"
    volumes:
        - ./:/app
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
  php:
    image: php:7-fpm
    command:
      - /bin/sh
      - -c
      - |
          docker-php-ext-install mysqli 
          echo "extension installed.....starting php-fpm........................................"
          php-fpm
    volumes:
        - ./:/app
  db:
    image: mysql
    container_name: banco_fgs
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini